server:
  port: 8081
  path: /hello
#spring:
#  profiles:
#    active: prod
person:
  last-name: lisi
  age: 12
  Integer: 18
  boss: false
  birth: 2017/12/12
  maps: {k1 : v1, k2: 12}
  lists:
    - lisi
    - zhangsan
  dog:
    name: xiaogou
    age: 2

---

server:
  port: 8084
spring:
  profiles: dev

---

server:
  port: 8085
spring:
  profiles: prod


#double quotes -> include escape characters
#single quotes -> won't include escape characters
#name: "zhang\nsan"
#sex: 'zhang\nsan'

#Objects
#friends:
#  lastName: zhuangsan
#  age: 20

#inline objects
#friends: {lastName: zhangsan, age: 18}

#Array
#pets:
#  - cat
#  - dog
#  - pig
#
#pets: [cat,dog,pig]


